### PR TITLE
Add ASAN and TSAN sanitizers

### PR DESCRIPTION
**Pull request by LinuxJedi**
New options for ASAN and TSAN sanitizers, it is recommended these are added to the CI process when issues they find are fixed.

ASAN finds leaks, similar to valgrind but is compiled in and much faster. TSAN finds thread issues such as race conditions.

You can enable them using -DWITH_ASAN or -DWITH_TSAN. They cannot be used at the same time.

### CODE REVIEW

**Review by davidducos — APPROVED** [review]

**Comment by davidducos** [comment]
Hi @LinuxJedi, This failed for Bionic, Xenial and EL7.

**Comment by LinuxJedi** [comment]
@davidducos  you mean when ASAN or TSAN is enabled? Yes, there are issues that need resolving. This is just the tools to detect them.

If you mean this breaks the build, do you have a link or more info? It worked on those platforms on my servers.

**Comment by davidducos** [comment]
@LinuxJedi 
I rebuild my xenial VM and I got the same issue, reviewing just a bit about it I found that add_link_options was introduced in newer version of CMake that xenial doesn't have. So, in order to support old version too, I will create a PR. 
About the building process, I prefer to start working over CircleCI instead of sharing mine (https://github.com/mydumper/mydumper/issues/835) as I think that it will be more valuable.

**Comment by LinuxJedi** [comment]
Ah! My bad, I already had an update CMake on my machines due to another project I work on.

**Comment by davidducos** [comment]
No worries! make sense now! I will be adding the PR later today.

**Pull request merged**
