### PR TITLE
Add minimal CircleCI config

### PR DESCRIPTION
**Pull request by SuperQ**
Add a simple build pipeline using CircleCI. This is just a first step.

This can be extended to test multiple combinations of different base
iamges, MySQL client libraries, and then integration tests with data.

Signed-off-by: SuperQ <superq@gmail.com>

### CODE REVIEW

**Comment by SuperQ** [comment]
@davidducos, this will require someone with maintainer access to configure integration with https://circleci.com/. There's a nice free tier for open source projects.

**Comment by SuperQ** [comment]
Ping @davidducos, what do you think about adding this?

**Comment by davidducos** [comment]
Hi @SuperQ,
I need to test it first and I didn't have much time. I will try to do it asap but not before next release which I will try to do it in 2 weeks. 
Btw, if you can provide me procedure to do this, that will be awesome. I already created my account on circleci

**Comment by davidducos** [comment]
@SuperQ, the other issue that I have is that MyDumper is not my repo and it is not an organization. This means that I don't have admin privileges, and I'm not allowed to create a project with MyDumper. And I don't want to branch to my account each time that I need to do a test... this is something that @maxbube and me, are already discussing. I will let you know. 
Please, don't forget about the 'tutorial'! thank you!

**Comment by SuperQ** [comment]
The CircleCI [getting started guide](https://circleci.com/docs/2.0/getting-started/?section=getting-started) pretty much covers it.

Basically once someone (maxbube in this case, since it's not an org project) needs to click through the integration buttons and that's it. It's pretty hands-off.

I'd be happy to help with the GitHub org stuff. I manage a bunch of that for the Prometheus monitoring project.

**Comment by SuperQ** [comment]
Are you still interested in adding CI to this project?

**Comment by davidducos** [comment]
Hi @SuperQ, yes, now that we had changed mydumper to org, I will be able to start to test it.

**Comment by SuperQ** [comment]
You can merge this, and then activate the integration. Or if you're ok with granting me contributor access, I can help with it.

After that is complete, I can make some additional PRs to setup more tests.

**Comment by davidducos** [comment]
@SuperQ, 
I'm currently just as `member` of the org, I think that we need to change my role to `owner` to be able to add you, I will talk with @maxbube to allow you to be a contributor. 
Meanwhile, I will approve this a test it, but YES! your help will be appreciated!!

**Review by davidducos — APPROVED** [review]

**Pull request merged**
