### PR TITLE
Fix: myloader fails to restore table that references sequence + stability fixes

### PR DESCRIPTION
**Pull request by midenok**
CREATE TABLE fails if table referencing sequence is restored before sequence. This can happen because sequence restore happens at the very late stage of view restore. To fix this we move sequences restore in between database and table schema restore.

We enqueue sequences to buffer queue database::sequence_queue like it is done for tables with database::queue. And we requeue sequence_queue before tables queue in set_db_schema_state_to_created().  We trigger reque like for tables: after database schema was created. When all sequences processed (sequences_processed == sequences) we requeue tables same way in set_db_schema_state_to_created().

There are 2 stages in INTERMEDIATE_ENDED. When first stage entered we wait until all sequences processed and then initiate for all dbs set_db_schema_state_to_created() which requeues their tables into creating queue.

Bug description:

https://jira.mariadb.org/browse/CONTRIB-25

Fixes mydumper/mydumper#1338

### CODE REVIEW

**Comment by davidducos** [comment]
Hi @midenok please, send me a request when a PR is ready to review.

Cheers

**Comment by midenok** [comment]
@davidducos What request? PR is the request itself. It's ready for review.

**Comment by davidducos** [comment]
Hi @midenok, 
As we have all those checks, it is possible that a PR fails and needs some rework. 
That is why, sometimes a PR is not ready to review. 
You can request review from here:
image

Let me know if that works for you and if you are willing to add you as Collaborator to the project.

**Comment by davidducos** [comment]
Hi @midenok 
I think that you are missing a scenario. If you have a sequence loaded after the table, then myloader will not be able to know that there is a sequence that needs to be processed. 
I think that you need to flag the tables that use sequence and hold only those tables, not the entire backup.

**Comment by midenok** [comment]
> Hi @midenok I think that you are missing a scenario. If you have a sequence loaded after the table, then myloader will not be able to know that there is a sequence that needs to be processed.

It counts sequences in `process_metadata_global()` (before reading filesystem).

> I think that you need to flag the tables that use sequence and hold only those tables, not the entire backup.

But this is not possible without proper SQL parser, is it?

**Comment by davidducos** [comment]
> > Hi @midenok I think that you are missing a scenario. If you have a sequence loaded after the table, then myloader will not be able to know that there is a sequence that needs to be processed.
> 
> It counts sequences in `process_metadata_global()` (before reading filesystem).

it is not guarantee when you are using stream.

> 
> > I think that you need to flag the tables that use sequence and hold only those tables, not the entire backup.
> 
> But this is not possible without proper SQL parser, is it?

I think that this query should work:
```
select TABLE_NAME from information_schema.COLUMNS where COLUMN_DEFAULT like 'nextval%' and DATA_TYPE like '%int';
```

**Comment by midenok** [comment]
> > > Hi @midenok I think that you are missing a scenario. If you have a sequence loaded after the table, then myloader will not be able to know that there is a sequence that needs to be processed.
> > 
> > 
> > It counts sequences in `process_metadata_global()` (before reading filesystem).
> 
> it is not guarantee when you are using stream.

What does this mean? It doesn't send metadata first in stream?

> 
> > > I think that you need to flag the tables that use sequence and hold only those tables, not the entire backup.
> > 
> > 
> > But this is not possible without proper SQL parser, is it?
> 
> I think that this query should work:
> 
> ```
> select TABLE_NAME from information_schema.COLUMNS where COLUMN_DEFAULT like 'nextval%' and DATA_TYPE like '%int';
> ```

There is not only nextval(), there is lastval(). There may be more functions in future. There is not only default expressions, but check and virtual column expressions as well. It may be not simple `nextval(x)` expression but any math expression: `(5 + nextval(x) + lastval(y)) * nextval(z)`, etc.

**Comment by davidducos** [comment]
@midenok how does MariaDB version of mysqldump to sort this issue out???

**Comment by midenok** [comment]
> @midenok how does MariaDB version of mysqldump to sort this issue out???

It dumps sequences first, I guess.

**Comment by davidducos** [comment]
Ok, then we need to do on mydumper:
1- Split the table selection, we have to select the sequence with:
```
select TABLE_SCHEMA,TABLE_NAME from information_schema.TABLES where TABLE_TYPE = 'SEQUENCE';
```
And the remaining tables
2- We need to count the sequence. 
3- We are going to send the sequence first because stream needs it asap. Once all the sequence jobs are done, we start sending the tables.
4- We save the amount of sequence on metadata.

On myloader:
- if it is from directory, we need to read the amount of sequence and do not create the tables until we create the tables as you already did on this PR
- if it is stream there shouldn't be any issue, as the sequence are coming first but we could also check on metadata partial the amount of sequence that we need to execute to allow to create tables

@midenok you will need to add support for stream.

**Comment by midenok** [comment]
> Ok, then we need to do on mydumper: 1- Split the table selection, we have to select the sequence with:
> 
> ```
> select TABLE_SCHEMA,TABLE_NAME from information_schema.TABLES where TABLE_TYPE = 'SEQUENCE';
> ```
> 
> And the remaining tables 2- We need to count the sequence. 3- We are going to send the sequence first because stream needs it asap. Once all the sequence jobs are done, we start sending the tables. 4- We save the amount of sequence on metadata.
> 
> On myloader:
> 
> * if it is from directory, we need to read the amount of sequence and do not create the tables until we create the tables as you already did on this PR
> * if it is stream there shouldn't be any issue, as the sequence are coming first but we could also check on metadata partial the amount of sequence that we need to execute to allow to create tables
> 
> @midenok you will need to add support for stream.

Let's do one step at a time! I'm not sure my customer needs stream usage, OTOH everybody will benefit from sequences working in file dump. You should open bug report for the part of streaming. Meanwhile I've been busy with a lot of stability fixes. Here in this patch I added them.

**Comment by midenok** [comment]
Duplicates #1355

**Pull request closed without merging**
