### PR TITLE
Remove drizzle support

### PR DESCRIPTION
**Pull request by morgo**
This PR does the following:

* Removes support for drizzle, and simplifies a number of if statements.
* Previously MariaDB was flavor detected and then handled the same as MySQL, but this is likely to cause problems already. So I have changed it to say it is "MariaDB".

After this PR, the only special flavor detection is for TiDB, although within the code there is version detection. In future it makes sense to extend the flavor detection to also handle Percona Server because of this line in `mydumper.c`:

```
      if (!g_str_has_prefix("Percona", ver[0]) &&
```

I ran `clang-format` over files after editing them to ensure indentation was fixed.

### CODE REVIEW

**Comment by davidducos** [comment]
@morgo there a couple of reviews in the code, let me know your thoughts, so I can merge this code.

**Comment by morgo** [comment]
> @morgo there a couple of reviews in the code, let me know your thoughts, so I can merge this code.

I can't see them yet. Is it possible they are still a draft?

**Comment by davidducos** [comment]
@morgo can you check again?

**Comment by morgo** [comment]
> @morgo can you check again?

sorry, there are no review comments yet :(

**Comment by davidducos** [comment]
I'm going to close this and create a new issue to review the code when DETECT_SERVER is being used

**Pull request closed without merging**
